---
- name: Create app directory
  file:
    path: /opt/app
    state: directory

- name: Copy docker-compose.prod.yml
  copy:
    src: ../../../../docker-compose.prod.yml
    dest: /opt/app/docker-compose.prod.yml

- name: Create nginx config directory
  ansible.builtin.file:
    path: /opt/app/deployments/nginx
    state: directory
    mode: '0755'

- name: Copy nginx default.conf
  copy:
    src: ../../../../deployments/nginx/default.conf
    dest: /opt/app/deployments/nginx/default.conf

- name: Log in to GitHub Container Registry
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ lookup('env', 'GHCR_USERNAME') }}"
    password: "{{ lookup('env', 'GHCR_PASSWORD') }}"

- name: Start application
  community.docker.docker_compose_v2:
    project_src: /opt/app
    files:
      - docker-compose.prod.yml
    state: present