---
- name: Create app directory
  file:
    path: /opt/app
    state: directory

- name: Copy docker-compose.prod.yml
  copy:
    src: ../../../../docker-compose.prod.yml
    dest: /opt/app/docker-compose.prod.yml

- name: Copy frontend directory
  copy:
    src: ../../../../frontend
    dest: /opt/app

- name: Copy backend directory
  copy:
    src: ../../../../backend
    dest: /opt/app

- name: Copy deployments directory
  copy:
    src: ../../../../deployments
    dest: /opt/app

- name: List contents of /opt/app
  ansible.builtin.command: ls -la /opt/app
  register: ls_opt_app
  changed_when: false

- name: Debug /opt/app contents
  ansible.builtin.debug:
    var: ls_opt_app.stdout_lines

- name: Build Docker images
  community.docker.docker_compose_v2:
    project_src: /opt/app
    files:
      - docker-compose.prod.yml
    build: always

- name: Start application
  community.docker.docker_compose_v2:
    project_src: /opt/app
    files:
      - docker-compose.prod.yml
    state: present