---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "git"]
    state: present