services:
  backend:
    image: ghcr.io/ihasidul/padre-ginos-pizza-backend:latest
    volumes:
      - ./backend/backend-data:/app/backend-data
    environment:
      - NODE_ENV=production

  frontend-builder:
    image: ghcr.io/ihasidul/padre-ginos-pizza-frontend:latest
    volumes:
      - frontend-dist:/app/dist

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${PWD}/deployments/nginx/:/etc/nginx/conf.d/
      # - ${PWD}/deployments/nginx/:/etc/nginx/conf.d/
      - frontend-dist:/usr/share/nginx/html
    depends_on:
      - frontend-builder
      - backend

volumes:
  frontend-dist:
