services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app # Mount entire backend for local development
      - /app/node_modules # Exclude node_modules from host mount
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      target: build # Use the build stage from the Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
