services:
  backend:
    image: ghcr.io/ihasidul/padre-ginos-pizza-backend:latest
    volumes:
      - ./backend/backend-data:/app/backend-data
    environment:
      - NODE_ENV=production

  frontend:
    image: ghcr.io/ihasidul/padre-ginos-pizza-frontend:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend