services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/backend-data:/app/backend-data # Persist SQLite DB on host
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
