version: "3.8"
services:
  backend:
    image: ghcr.io/ihasidul/padre-ginos-pizza-backend:latest
    volumes:
      - ./backend/backend-data:/app/backend-data
    environment:
      - NODE_ENV=production

  frontend:
    image: ghcr.io/ihasidul/padre-ginos-pizza-frontend:latest
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deployments/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
