services:
  backend:
    build: ./backend
    volumes:
      - ./backend/backend-data:/app/backend-data
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deployments/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
